### ISSUE TITLE
Quest Book Enchantment: Incorrect Enchantment on Soulbinding reward

### ISSUE THREAD

**Issue by NevadaActual** [Wizelf402/Permafrost#14]
Title. Soulbinding has the enchant "lvl: 1s" whereas the reward has enchant "lvl: 1b." As such, Soulbinding cannot stack with the quest book reward. Extremely minor bug, implementation should wait until quest book changes, as a whole, are near finalized.

**Comment by rinOfTheStars** [comment]
Will be fixed with an upcoming update.
