### ISSUE TITLE
Singleplayer server intermittently crashes, requiring hard resets.

### ISSUE THREAD

**Issue by moonbeast32** [Wizelf402/Permafrost#18]
Every so often, my world stops working. I don't mean that the game itself crashes, but suddenly I can't open chests, mobs stop moving, blocks stop dropping, etc. Things continue in that fashion indefinitely until I hard-reset the client. I cant even "save and quit" because if I do, I get stuck on the "saving world data" page forever.

Additional info: 
I use Cinnamon Mint (Ubuntu) OS. My launcher is MultiMC. I have 9 gigs of ram allocated for Minecraft. I have no other major technical issues other than this one. My computer handles the rest of the game just fine.

Here is a link to my log:
https://pastebin.com/9misZevF

**Comment by NevadaActual** [comment]
This is the same issue as #11, it's related to Apotheosis spawning. We'll get a fix up soon, but it'll take a day or three cause of life things on Wiz's end. In the meantime, try to disable the Deadly module in the apotheosis config, in the directory instances/Permafrost/config/apotheosis.
