### ISSUE TITLE
Loading an older save in 1.2 has the questbook in Edit Mode

### ISSUE THREAD

**Issue by Minithra** [Wizelf402/Permafrost#23]
Pack version 1.2, world created in 1.1.6. Crashed the first time I tried to load, worked fine the second time, except the quest book is in edit mode, no idea how to fix it

**Comment by rinOfTheStars** [comment]
@Wizelf402 I suspect this has something to do with the configs for HQM having edit mode turned on in them somehow: could you verify this (and make sure it's fixed for 1.2.1) if ya can?

**Comment by rinOfTheStars** [comment]
Will be fixed with an upcoming update.
