### ISSUE TITLE
Hardcore worlds are converted to Survival on generation.

### ISSUE THREAD

**Issue by NevadaActual** [Wizelf402/Permafrost#24]
Hardcore doesn't lock difficulty, or limit respawns. On inspection of the world loading screen, the world (which should read as Hardcore) is instead a Survival world. Creative worlds generate without issue, so what could be causing this?

**Comment by rinOfTheStars** [comment]
Suspect it's because of HQM; probably tries to override the Hardcore mode from vanilla with its hardcore-with-extra-lives thing and doesn't do a very good job of it. Possibly cantfix worthy?

**Comment by Wizelf402** [comment]
Sure is a cantfix thing. However, making a hardcore world is still possible using HQM. All you've gotta do is set the "hardcore:false" thing in the config to "hardcore:true"

**Comment by NevadaActual** [comment]
To add to this, creative worlds are also overwritten. Something is screwy with worldgen and gamerule settings, cause they just get ignored on New World. Reopening while I investigate a bit.

**Comment by NevadaActual** [comment]
orrrrr at least they were till a recent version. Not sure what changed, but it's only Hardcore worlds that get overwritten. Closing as the issue is cantfix
