### ISSUE TITLE
Nether fortresses failing to generate chests and spawners

### ISSUE THREAD

**Issue by TheExtraChromosome** [Wizelf402/Permafrost#25]
Easy to reproduce, simply go to the nether, find a fortress, and find a blaze spawn platform- no spawners.
Chests are clearly absent as well after checking multiple fortresses.

Blaze pillars and bastions generate spawners and chests correctly and consistently, issue is unique to nether fortresses

**Comment by rinOfTheStars** [comment]
Oh god this is really funky, I'll investigate when i can

**Comment by TheExtraChromosome** [comment]
Additional information from **1.3**
Issue extends to desert temples, no chests.
Chests (both vanilla and modded variants), and spawners seem to be generating correctly in lost cities, stray towers, battle towers, shipwrecks, zombie villages and ruined portals.

**Comment by TheExtraChromosome** [comment]
Re-tested in 1.3.1
Chests/spawners are present at shipwrecks, buried treasure, dungeons, apotheosis cave and boss spawners, igloos, battle towers, warped gardens, dragon nests, lost cities, cyclops caves, ancient leviathans, blaze pillars, bastion remnants

Chests, dispensers and spawners are NOT generating in desert temples, jungle temples, or nether fortresses.

**Comment by TheExtraChromosome** [comment]
Issue corrected in 1.3.3, closing the thread!
