### ISSUE TITLE
Apotheosis boss item crashes

### ISSUE THREAD

**Issue by Spaig** [Wizelf402/Permafrost#33]
Getting server crashes semi-randomly from Apotheosis - probably related to boss item generation. Used to get these on 1.2, they stopped when we upgraded to 1.3, we upgraded to 1.3.5 the other day and they're baaaack

example crash log is here: https://pastebin.com/ja5rxm5W
We have about seven essentially identical crash logs, first few lines say

java.lang.NullPointerException: Exception in server tick loop
	at shadows.apotheosis.util.RandomAttributeModifier.apply(RandomAttributeModifier.java:40) ~[apotheosis:4.6.1] {re:classloading}
	at shadows.apotheosis.deadly.gen.BossItem.initBoss(BossItem.java:134) ~[apotheosis:4.6.1] {re:classloading}

**Comment by NevadaActual** [comment]
Messaged someone on the discord about it, they'll get back to me with specifics. Sounds like a specific issue with your server config, but we'll have to wait for further info.

**Comment by NevadaActual** [comment]
Worked with server admin, will get feedback soon regarding the specifics of the issue.

**Comment by NevadaActual** [comment]
Problem appears to be resolved, the correct files were not installed.
