### ISSUE TITLE
Unable to get water for drinking

### ISSUE THREAD

**Issue by GottJammern** [Wizelf402/Permafrost#4]
As title. The only way to get purified water in a bottle involves an 'uncraftable potion' being cooked. No way to make a wooden bowl of purified water as I can't cook a regular water bowl anywhere.
 I can't even fill a glass bottle with water from a source block of water, though filling bowls works just fine.
I'm totally confused.

**Comment by Nayoh7467** [comment]
You can fill up bottles using a cauldron and throw them in a furnace! Not sure why we can't grab it from source blocks, but the cauldron works atm.

**Comment by GottJammern** [comment]
Odd, when I use JEI to find the recipe for purified water bottles it says the only recipe in a furnace is with the previously mentioned 'uncraftable potion'. I'll have to test it out tonight.

**Comment by GottJammern** [comment]
Odd. You can certainly cook water.bottles in a furnace, though JEI says you can't.
