### ISSUE TITLE
Cold Resistance potion recipes are innacurate

### ISSUE THREAD

**Issue by pyrebuilder** [Wizelf402/Permafrost#44]
Per JEI the cold resistance potion can be crafted two ways:
Three awkward potions and one ice cube in a brewing stand
or
Four awkward potions worth (100mb) and one ice cube in an automated mixer

The crewing stand will not accept the ice cube, and spits it back out once the dialogue window for the stand is closed (placing it directly back into your inventory instead of into the world)

**Comment by NevadaActual** [comment]
Ah, JEI is actually incorrect.
Moonstone is supposed to be the recipe that creates cold res pots. We'll look into fixing this one quickly, I've had to let a ton of people know about the right recipe.

**Comment by pyrebuilder** [comment]
So then a more accurate report of the issue would be:
"JEI reflects Cold resistance potions as being created using ice cubes, this incorrect recipe functions in the automated mixer, but not in the brewing stand"

**Comment by pyrebuilder** [comment]
Newest version provides specific recipe
