### ISSUE TITLE
Crash of client when placing Magma Shrine

### ISSUE THREAD

**Issue by pyrebuilder** [Wizelf402/Permafrost#48]
Not sure if it's specific to my setup or not, but whenever I try to place a magma shrine, my client crashes. I've tried it 4 times.
I'm playing on a 4k monitor with a GTX 980 GPU in case those things matter, let me know if there's any other data I can provide.

Uploaded log:
https://paste.ee/p/Gcdx4

**Comment by Wizelf402** [comment]
Heya! This problem was verymuch present in earlier versions of the pack,
due to a bug with HQM. Mind telling me what version you're usin?

**Comment by pyrebuilder** [comment]
Oops! 2.0 here lol, I somehow missed the many updates since then!!! Thank you, Wizelf!
