### ISSUE TITLE
TIMEOUT

### ISSUE THREAD

**Issue by leomcgoober** [Wizelf402/Permafrost#49]
It will not let me download the mod it will keep saying timeout downloading the mod and delete the mod.

**Comment by pyrebuilder** [comment]
What launcher are you using? MultiMC, the Forge launcher, Direwolf? And where are you downloading the mod from?

**Comment by leomcgoober** [comment]
just the one you get when you download Minecraft and curse forge

**Comment by leomcgoober** [comment]
yay you fixed it thatnk you

**Comment by leomcgoober** [comment]
thnks
