### ISSUE TITLE
Frozen enemies spawn all around me; cannot stop death loop

### ISSUE THREAD

**Issue by darchitectlp** [Wizelf402/Permafrost#56]
Currently playing Permafrost-5.0.zip

Loving the pack so far. Couple hours in, and there was a sort of twanging noise while mining. A moment later, around 20 frozen mobs spawned all around me killed me quickly (literally around me; several were forced into walls and died). I respawned and another batch of 20 or so frozen mobs spawned all around my bed (in my rather small cave) and killed me again. This happened several times. Eventually, I had to go into creative mode and /kill all of them. While still in creative mode, another batch spawned again. Not sure what's happening here, but guessing that's not how it's intended to play out.

Thanks!

**Comment by darchitectlp** [comment]
Ok, looks like it's an issue with The Hordes; already been posted on the issues page there. Will disable mod for now.

https://github.com/SmileycorpMC/The-Hordes/issues/8

**Comment by darchitectlp** [comment]
Ok, looks like it's an issue with The Hordes; already been posted on the issues page there. Will disable mod for now.

https://github.com/SmileycorpMC/The-Hordes/issues/8

**Comment by darchitectlp** [comment]
Ok, looks like it's an issue with The Hordes; already been posted on the issues page there. Will disable mod for now.

https://github.com/SmileycorpMC/The-Hordes/issues/8

**Comment by darchitectlp** [comment]
Ok, looks like it's an issue with The Hordes; already been posted on the issues page there. Will disable mod for now.

https://github.com/SmileycorpMC/The-Hordes/issues/8](https://github.com/SmileycorpMC/The-Hordes/issues/8

**Comment by darchitectlp** [comment]
Ok, looks like it's been fixed by upgrading The Hordes to The-Hordes-1.16.5-1.1.4a.jar and Atlas Library to Atlas-Lib-1.16.5-1.1.3c.jar.

**Comment by darchitectlp** [comment]
Thanks for the update; I will say, I'm still having issues with the Hordes mod. I've got a bug posted there, but I haven't gotten to play to test again. It looks like it isn't respecting the spawnVariation... I've got hordes showing up in the middle of the day. You may want to play test, too (with a new world).

**Comment by NevadaActual** [comment]
I'm unsure whether this mod is even used in this modpack, I can't seem to find this on my local copy of the pack. I'm going to close this assuming it hasn't been an issue because of a change, deliberate or not, since this post was made. If this still occurs for you, comment and I'll reopen this for a serious investigation.
