### ISSUE TITLE
"Going Deeper" Not Registering

### ISSUE THREAD

**Issue by AussieGiant** [Wizelf402/Permafrost#6]
After entering the Nether and getting the advancement "We need to go deeper" the quest "Going Deeper" even upon clicking the manual detect button does not correctly register. Using cheat commands to revoke this advancement and then gettig it again also does not fix.
In addition to this the hardcore questing commands seem to not work not allowing the manual setting of this quest.

**Comment by Wizelf402** [comment]
heya, thanks for lettin' me know about this! I'll do what I can to fix the problem ASAP, once the more pressin' shit's dealt with.
