### ISSUE TITLE
End Remastered eyes not appearing in loot (and other loot questions)

### ISSUE THREAD

**Issue by darchitectlp** [Wizelf402/Permafrost#62]
Been playing awhile now, and couldn't find a single eye from End Remastered... looks like End Remastered had an issue where it wasn't putting the eyes into the loot tables... I updated to End Remastered 1.16.3+ R4.1.1, and found an corrupted eye immediately upon finding an illager outpost. You may want to verify this, though, as the changelog for the 1.16 versions didn't mention this fix; only that it happened to the 1.17 version.

The new version changes the eye names, though, so you'll need to fix your scripts.

Also, after playing for a long time, I expected adjusted loot. Everything looks pretty basic in all the added structures and dungeons. I was wondering if that was an error... I expected to find cold resist/heat resist potions in roguelike dungeons... or maybe base shrines from elementalcraft or other mod related loot, especially on the lower floors. Maybe the odd bit of moonstone or a Botania rune. 

All that said, this is a great pack and I hope you have the time and energy to keep working on it.

**Comment by Wizelf402** [comment]
Okay. Question. What version were you on?

**Comment by darchitectlp** [comment]
Permafrost 5.0 and EndRemastered-R36.jar. Looks like you just updated. I'll download and see if I can find eyes in structures in new chunks. Will update you.

**Comment by darchitectlp** [comment]
Looks like all is working; found 2 already! You may have saved the HQM book in edit mode... or it may be a setting that puts it in edit mode for single player. Not a big deal. Thanks!

**Comment by darchitectlp** [comment]
Heya, looks like you didn't update the advancement names in the HQM book from _pearl to _eye so when I'm finding the eyes, HQM doesn't register the advancement.

**Comment by Wizelf402** [comment]
Ty ty, this should be fixed now

**Comment by NevadaActual** [comment]
Likely fixed, closing issue.
