### ISSUE TITLE
chickens keep despawning 

### ISSUE THREAD

**Issue by legitkingyolo1** [Wizelf402/Permafrost#7]
I have like 16 chickens and went to go mine and then they disappear, I have campfires around the fences and torches up but they still keep disappearing.

**Comment by legitkingyolo1** [comment]
spawned more chickens zombie spawned in my base when i came back and then all the chickens disappeared

**Comment by NevadaActual** [comment]
Can you please provide more detail? I'm not entirely sure how to go about testing this, as "chickens disappearing" is fairly vague. Distance, both vertical and horizontal, time, and potential causes are all appreciated.

**Comment by rinOfTheStars** [comment]
I'll see if i can contact legitkingyolo1 on discord. If this actually a bug, it might be bc the mobs aren't considered to be owned by the player and so despawn; though I'm not sure as I haven't reached this phase in the pack yet in SP

**Comment by NevadaActual** [comment]
If legitkingyolo1 does respond, please direct him to https://minecraft.fandom.com/wiki/Spawn#Despawning to confirm that vanilla mob handling was not a possibility.

**Comment by NevadaActual** [comment]
As legit has not responded since we've attempted to make contact with him, I'm closing the issue. If legit comes back with more information, please respond to this issue so we can reopen and resolve it.
